---
- hosts: localhost
  gather_facts: true
  become: true
  tasks:
  - name: stop myserver instance
    local_action:
       module: ec2
       region: us-east-2
       instance_ids: ['i-0f4744aa38a9f97c7']
       state: stopped
...
