---
- hosts: localhost
  gather_facts: true
  become: true
  tasks:
  - name: stop myserver instance
    local_action:
       module: ec2
       region: "{{ region }}"
       instance_ids: "{{ instance_ids }}"
       state: "{{ state }}"
...
