---
- hosts: webservers
  gather_facts: true
  become: true
  tasks:
  - name: stop myserver instance
    local_action:
       module: ec2
       region: us-east-2
       instance_ids: ['i-0624787262e1f73ba']
       state: running
...
