---
- name: installing lamp
  hosts: webservers
  gather_facts: true
  become: true
  tasks:
  - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  - hosts: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
  - name: Installing Apache, MYSQL & PHP
    yum:
      name:
        - httpd
        - mariadb-server
        - mariadb-devel
        - php
        - php-mysql
      state: installed
  - name: Enabling httpd service and start the service
    service:
      name: httpd
      enabled: yes
      state: started
  - name: Enabling mysql service and start the service
    service:
      name: mariadb
      enabled: yes
      state: started
  - name: Copying php file in the /var/www/html
    copy:
      src: index.php
      dest: /var/www/html/index.php
      force: yes

...
