---
- name: launching ec2
  ec2:
   instance_type: "{{ instance_type }}"
   key_name: "{{ key_pair }}"
   image: "{{ image_id }}"
   region: "{{ region }}"
   group: default
   count: 1
   vpc_subnet_id: "{{ vpc_subnet_id }}"
   wait: yes
   assign_public_ip: yes
   state: "{{ state }}"
   instance_tags: {"key":"value"}
